apiVersion: v2
name: jumpcloud-teleport-sync
description: Syncs JumpCloud group members to Teleport Community Edition as local users
type: application
version: 0.2.1
appVersion: "1.0.0"
keywords:
  - teleport
  - jumpcloud
  - scim
  - sync
