{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jumpcloud-teleport-sync.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jumpcloud-teleport-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  JUMPCLOUD_CLIENT_ID: {{ required "jumpcloudClientID is required when existingSecret is not set" .Values.jumpcloudClientID | quote }}
  JUMPCLOUD_CLIENT_SECRET: {{ required "jumpcloudClientSecret is required when existingSecret is not set" .Values.jumpcloudClientSecret | quote }}
  JUMPCLOUD_ORG_ID: {{ required "jumpcloudOrgID is required when existingSecret is not set" .Values.jumpcloudOrgID | quote }}
{{- end }}
---
{{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jumpcloud-teleport-sync.fullname" . }}-smtp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jumpcloud-teleport-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_USERNAME: {{ required "smtp.username is required when smtp.enabled is true and smtp.existingSecret is not set" .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ required "smtp.password is required when smtp.enabled is true and smtp.existingSecret is not set" .Values.smtp.password | quote }}
{{- end }}
