{{- if .Values.setup.enabled }}
# The setup hook needs to kubectl exec into the Teleport auth pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jumpcloud-teleport-sync.fullname" . }}-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jumpcloud-teleport-sync.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jumpcloud-teleport-sync.fullname" . }}-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jumpcloud-teleport-sync.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jumpcloud-teleport-sync.fullname" . }}-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jumpcloud-teleport-sync.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jumpcloud-teleport-sync.fullname" . }}-setup
subjects:
  - kind: ServiceAccount
    name: {{ include "jumpcloud-teleport-sync.fullname" . }}-setup
    namespace: {{ .Release.Namespace }}
{{- end }}
